### ISSUE TITLE
Missing optional path parameter throws error for addPackageDependencies

### ISSUE THREAD

**Issue by dptoot** [sindresorhus/write-pkg#22]
The docs state that the path parameter is optional for addPackageDependencies

`addPackageDependencies(path?, dependencies, options?)`

but without it I am getting an error

`
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at hasMultipleDependencyTypes (<redacted>/node_modules/write-pkg/source/util.js:11:66)
    at addPackageDependencies (<redacted>/node_modules/write-pkg/source/add-remove-dependencies.js:9:9)
`

**Comment by sindresorhus** [comment]
// @tommy-mitchell
